config/routes.rb
Rails.application.routes.draw do

  root to: "site#index"

  get 'site/about'
  get 'articles/user_articles'
  get 'users/current'
  get 'users/group'
  get 'users/articles'

  resources :groups do
    get 'articles'
  end
  
  resources :articles do
    member do
      get 'r'
    end
  end
  resources :annotations
  devise_for :users

  resources :users 

  mount Api => '/api/'

end

app/models/annotation.rb
class Annotation < ActiveRecord::Base
  validates :range, presence: true
  validates :quote, presence: true
  validates :tag, presence: true

  belongs_to :user
  belongs_to :article

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  
  has_many :comments
  has_many :annotations
  
  validates :title, presence: true
  # validates :pdf, presence: true
  validates :path_type, presence: true
  
  mount_uploader :pdf, PdfUploader

  self.per_page = 8
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :ty, presence: true, inclusion: { in: ['as', 'is'] }
  varldates :si, presence: true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :usergroups
  has_many :users, :through => :usergroups
  has_many :articles

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :annotations
  has_many :articles
  has_many :usergroups
  has_many :groups, :through => :usergroups

  before_create :generate_authentication_token

  def generate_authentication_token
    loop do
      self.authentication_token = SecureRandom.hex 20
      break unless self.class.exists?(authentication_token: authentication_token)
    end
  end

end

app/models/usergroup.rb
class Usergroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
 def index
    @annotations = Annotation.paginate(:page => params[:page])
  end

  def show
    @annotation = Annotation.find_by_id(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.where(public: 0).paginate(:page => params[:page])
  end

  def r
    @r = Article.where(public: 0).find_by_id(params[:id])
  end
  
  def show
    @article = Article.find_by_id(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :path_type, :pdf, :public, :group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def articles
    @group = Group.find(params[:group_id])
    @articles = @group.articles
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.admin_id = current_user.id
    @group.save
    Usergroup.create(:group => @group, :user => current_user)
    respond_with(@group, :location => users_group_path)
  end

  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:title, :desc, :count, :admin_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'home', :only => [:index]

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def current
    @user = current_user
  end

  def group
    @groups = current_user.groups
  end

  def articles
    @articles = current_user.articles.paginate(:page => params[:page])
  end
end

app/helpers/annotation_helper.rb
module AnnotationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/annotations/index.html.haml
.row
  .large-12.columns
    #main-content.wrap
      #u-annotations
        .row.border-bottom
          .large-4.columns
            %h5 批注
          .large-3.columns
            %p 评论
          .large-1.columns
            %p 类型
          .large-2.columns
            %p 文章
          .large-2.columns
            %p 创建于
        - @annotations.each do |annotation|
          .row.border-bottom
            .large-4.columns
              %h5
                = link_to annotation.quote, ''
            .large-3.columns 
              - if annotation.text?
                %p= annotation.text
              - else
                %p= ''
            .large-1.columns
              - if annotation.tag == 'star'
                %p.label.radius 重点
              - if annotation.tag == 'comment'
                %p.label.radius 评论
            .large-2.columns
              %p= link_to annotation.article.title, article_path(annotation.article.id)
            .large-2.columns
              %p= annotation.created_at.strftime("%m月%d号")

    = will_paginate @annotations

app/views/annotations/show.html.haml
.row
  .large-12.columns
    #main-content.wrap
      %h4= @annotation.text

app/views/articles/index.html.haml
.row
  .large-12.columns
    #main-content.wrap
      #y-articles

    = will_paginate @articles

%script{type: 'text/template', id: 't-article'}
  %h4 
    %a{:href => "/articles/{{= article.id }}/r"}{{= article.title}}
  %p {{= article.body }}

- articles_json = render template: "articles/index", formats: [:json], handlers: [:jbuilder]

= content_for :js_ext do
  :javascript
    $(document).ready(function () {
      var articles_view = new Coreading.Views.Articles.ArticlesView(#{articles_json});
    });
    $('.articles-btn').addClass('active');

app/views/articles/new.html.haml
.wrap
  %h3.text-center 添加文章
  = form_for(@article) do |f|
    - if @article.errors.any?
      #error_explanation
        %h2
          = pluralize(@article.errors.count, "error")
          prohibited this article from being saved:
        %ul
          - @article.errors.full_messages.each do |message|
            %li= message
    .row
      = f.label :title, '标题'
      = f.text_field :title
    .row#path-type
      %label 文章来源
      = f.radio_button :path_type, 'pdf'
      = f.label :path_type_pdf, '上传'
      = f.radio_button :path_type, 'online'
      = f.label :path_type_online, '在线编辑'
    .row#online-content
      = f.label :body, '正文'
      = f.text_area :body
    .row#pdf-upload-content
      = f.label :pdf, '上传 pdf 文件'
      = f.file_field :pdf
    .row#public-type
      %label 权限
      = f.radio_button :public, '0'
      = f.label :public_0, '公开'
      = f.radio_button :public, '1'
      = f.label :public_1, '组'
      = f.radio_button :public, '2'
      = f.label :public_2, '私有'
    .row#group-select-content
      = f.select :group_id, options_for_select(current_user.groups.collect{|g| [g.title, g.id]})
    .actions
      = f.submit '创建', class: 'button tiny'
      = link_to '返回', users_articles_path, class: 'button tiny'
      
= content_for :js_ext do
  :javascript
    $('#online-content').hide();  
    $('#group-select-content').hide();
    $('#path-type input').change(function(){
      if($('#article_path_type_pdf').prop('checked')){
        $('#pdf-upload-content').show();
        $('#online-content').hide();
      } else {
        $('#pdf-upload-content').hide();
        $('#online-content').show();      
      }
    });
    $('#public-type').change(function(){
      if($('#article_public_1').prop('checked')){
        $('#group-select-content').show();
      } else {
        $('#group-select-content').hide();
      }    
    })

app/views/articles/r.html.haml
.row
  .large-12.columns
    #main-content.wrap
      %h4= @r.title
      %p= @r.body

app/views/articles/show.html.haml
.row
  .large-12.columns
    #main-content.wrap
-# #chart-content
-#   %h5 最新动态
  
%script{type: 'text/template', id: 't-article-show'}
  %h2 {{= article.title}}
  %p {{= article.body }}
  #annotaions-meta

%script{type: 'text/template', id: 't-article-pdf-show'}
  %h2.text-center {{= article.title}}
  {{ if(article.public == 0) { }}
  %p.text-right 权限：公开
  {{ } else { }}
  %p.text-right 不公开
  {{ } }}
  .text-right
  {{ if(article.path_type == 'pdf') { }}
  %p.text-right 文章来源：上传 pdf
  {{ } else { }}
  %p.text-right 文章来源：在线
  {{ } }}
  #annotaions-meta
  #pdf-viewer-container
    #viewer.pdfViewer
  #annotator-wedget

%script{type: 'text/template', id: 't-annotation-meta'}
  .row
    .large-1.columns
      .label.radus 
        共
        %span#annotations-count{'data-annotations-count' => 0} 
          .fa.fa-spinner.fa-spin
        个批注
    .large-11.columns#annotations-users
      -# %p 批注成员
      -# #annotations-users{'data-users'}

- article_json = render template: "articles/show", formats: [:json], handlers: [:jbuilder]

= content_for :js_ext do
  :javascript
    $(document).ready(function () {
      var articles_view = new Coreading.Views.Articles.ArticleView(#{article_json});
    });

app/views/articles/user_articles.html.haml
.row
  .large-12.columns
    #main-content.wrap
      %a.button.tiny{:href => "/articles/new"} 创建
      #u-articles
        .row
          .large-6.columns
            %h5 标题
          .large-2.columns
            %p 批注数
          .large-2.columns
            %p 来源
          .large-2.columns
            %p 权限
        - @articles.each do |article|
          .row
            .large-6.columns
              %h5= link_to article.title, article_path(article.id)
            .large-2.columns
              %p= article.annotations.length
            .large-2.columns
              - if article.path_type == 'pdf'
                %p 上传 pdf
              - else
                %p 在线
            .large-2.columns
              - if article.public == 0
                %span.label.radius 公开
              - if article.public == 1
                %p 
                  %span.label.radius 组 
                  %span= article.group.title
              - if article.public == 2
                %p 个人

    = will_paginate @articles

= content_for :js_ext do
  :javascript
    $('.my-articles-btn').addClass('active');

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title, '标题'
    = f.text_field :title
  .field
    = f.label :desc, '描述'
    = f.text_area :desc
  .actions
    = f.submit '保存', class: 'button tiny'

app/views/groups/articles.html.haml
.wrap
  %h4 所有文章
  .row
    .large-8.columns
      %h5 标题
    .large-2.columns
      %p 批注数
    .large-2.columns
      %p 来源
      
  - @articles.each do |article|
    .row
      .large-8.columns
        %h5= link_to article.title, article_path(article.id)
      .large-2.columns
        %p= article.annotations.length
      .large-2.columns
        - if article.path_type == 'pdf'
          %p 上传 pdf
        - else
          %p 在线
    

app/views/groups/edit.html.haml
.wrap#main-content.group-edit-content
  %h3 小组管理
  %br

  .row
    .large-11.columns
      %h5 成员信息
    .large-1.columns.text-right
      #add-user-btn.fa.fa-plus-square
  %ul#user-list
  #add-user
  %hr
  %h5 文章信息
  #article-list
  %hr
  %h5 基本信息
  #edit-group
  %hr
  %h5 危险操作
  = link_to '删除', '#', class: 'button tiny', id: 'delete-group'

%script{type: 'text/template', id: 't-user'}
  %li.row.border-bottom{'data-username' => '{{= username }}'}
    .large-11.columns
      %h5 {{= username }}
    .large-1.columns.text-right
      %i.fa.fa-times.remove-user
%script{type: 'text/template', id: 't-article'}
  %li.row.border-bottom{'data-article-id' => '{{= article.id }}'}
    .large-6.columns
      %h5
        %a{:href => "/articles/{{= article.id}}"} {{=article.title}}
    .large-4.columns
      %p {{= article.created_at }}
    .large-1.columns
      %p {{= article.username }}
    .large-1.columns.text-right
      %i.fa.fa-times#remove-article

%script{type: 'text/template', id: 't-add-user-form'}
  %form.row
    .field.large-10.columns
      %label{for: 'username'} 
        用户名
        %input#username{name: 'username', type: 'text', placeholder: '输入用户名'}
    .field.large-2.columns
      %br
      .button.tiny#submit-add-user 确定
      .button.tiny#cancel-add-user 取消

%script{type: 'text/template', id: 't-edit-group'}
  %form  
    .field
      %label{for: 'title'} 标题
      %input#title{name: 'title', value: '{{= group.title }}', type: 'text'}
    .field
      %label{for: 'desc'} 描述
      %textarea#desc{name: 'desc'} {{= group.desc }}
    .field
      .button.tiny#save-meta 保存

- group_json = render template: "groups/show", formats: [:json], handlers: [:jbuilder]

= content_for :js_ext do
  :javascript
    $(document).ready(function () {
      var group_edit_view = new Coreading.Views.Groups.GroupEditView(#{group_json});
    });
    $('.my-groups-btn').addClass('active');

app/views/groups/index.html.haml
.wrap
  %h3 所有组

  %table
    %thead
      %tr
        %th 标题
        %th 描述
        %th 总数
        %th 管理员
        %th
        %th
        %th
        
    %tbody
      - @groups.each do |group|
        %tr
          %td= group.title
          %td= group.desc
          %td= group.count
          %td= User.find(group.admin_id).email
          %td= link_to '查看', group
          %td= link_to '编辑', edit_group_path(group)
          %td= link_to '删除', group, :method => :delete, :data => { :confirm => 'Are you sure?' }

  = link_to '创建组', new_group_path, class: 'button tiny'

app/views/groups/new.html.haml
.wrap
  %h3 创建组

  = render 'form'

app/views/groups/show.html.haml
.wrap
  %p#notice= notice

  %p
    %b 标题:
    = @group.title
  %p
    %b 描述:
    = @group.desc
  %p
    %b 总人数:
    = @group.count
  %p
    %b 管理员:
    = User.find(@group.admin_id).email

  = link_to '编辑', edit_group_path(@group), class: 'button tiny'

app/views/layouts/_nav.html.haml
.show-for-medium-up
  %nav.top-bar{:'data-topbar' => true}
    %ul.title-area
      %li.name
        %h1
          = link_to '/' do
            = image_tag("logo.png")
    %section.top-bar-section
      %ul.right
        %li.articles-btn
          = link_to articles_path do
            = "文章"
          - if user_signed_in?
            %li.my-articles-btn
              = link_to '我的文章', users_articles_path
            %li.my-groups-btn
              = link_to '我的小组', users_group_path
        %li.has-dropdown
          = link_to new_user_session_path do
            - if user_signed_in?
              = current_user.email
            - else
              登录
          %ul.dropdown
            - if user_signed_in?
              %li
                = link_to '我的批注', annotations_path
              %li
                %a{:href => "#"} 设置
              %li
                = link_to '登出', destroy_user_session_path, :method => 'delete', data: { confirm: '确定登出？'}
            - else
              %li
                = link_to '注册', new_user_registration_path
              %li
                %a{:href => "/site/random"} 关于

%nav.tab-bar.show-for-small-only
  %section.left-small.text-center
    %a.left-off-canvas-toggle
      %span
        %i.fa.fa-bars.defaultg
  %section.middle.tab-bar-section
    %h1.title CoReading
%aside.left-off-canvas-menu
  %ul.off-canvas-list
    %li.articles-btn
      = link_to articles_path do
        = "文章"
    - if user_signed_in?
      %li.my-articles-btn
        = link_to '我的文章', users_articles_path
      %li.my-groups-btn
        = link_to '我的小组', users_group_path
      %li
        = link_to '我的批注', annotations_path
      %li
        = link_to '登出', destroy_user_session_path, :method => 'delete', data: { confirm: '确定登出？'}
    - else
      %li
        = link_to '注册', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CoReading
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .off-canvas-wrap{:'data-offcanvas' => true}
      .inner-wrap
        = render :partial => 'layouts/nav'
        - if !notice.nil?
          .alert-box.success{:'data-alert' => true}
            = notice
            %a.close{:href => "#"} &times;
        - if !alert.nil?
          .alert-box.alert{:'data-alert' => true}
            = alert
            %a.close{:href => "#"} &times;
        .row
          .large-12.columns
            = yield

  :javascript
    $(document).foundation();
  = yield(:js_ext)

app/views/layouts/home.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title CoReading
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if !notice.nil?
      .alert-box.success{:'data-alert' => true}
        = notice
        %a.close{:href => "#"} &times;
    - if !alert.nil?
      .alert-box.alert{:'data-alert' => true}
        = alert
        %a.close{:href => "#"} &times;
    = yield
  :javascript
    $(document).foundation();
  = yield(:js_ext)

app/views/layouts/site.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CoReading
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render :partial => 'layouts/nav'
    - if !notice.nil?
      .alert-box.success{:'data-alert' => true}
        = notice
        %a.close{:href => "#"} &times;
    - if !alert.nil?
      .alert-box.alert{:'data-alert' => true}
        = alert
        %a.close{:href => "#"} &times;
    .row
      .large-12.columns
        = yield
  :javascript
    $(document).foundation();

app/views/site/about.html.haml
%h4 About

.content
  #viewerContainer
    #viewer.pdfViewer
  #annotator-wedget

:javascript
  var DEFAULT_URL = '/demo2.pdf';

  var container = document.getElementById('viewerContainer');
  var pdfViewer = new PDFJS.PDFViewer({
    container: container
  });

  container.addEventListener('pagesinit', function () {
    // we can use pdfViewer now, e.g. let's change default scale.
    pdfViewer.currentScaleValue = 'page-width';
  });

  // Loading document.
  PDFJS.getDocument(DEFAULT_URL).then(function (pdfDocument) {
    // Document loaded, specifying document for the viewer.
    pdfViewer.setDocument(pdfDocument);
  });
  Annotator.textSelector($('#viewerContainer'));
  Annotator.hoveHighlights();

app/views/site/index.html.haml
.container.home
  .page-1
    .row
      .large-12.columns.wrap
        .header-nav.show-for-small-only
          %ul
            %li.logo.text-right
              %a{:href => "/"}
                %h3.white CoReading
            %li.text-right
              %a.white{:href => "/articles"} 文章
        .header-nav.show-for-medium-up
          %ul
            %li.logo.text-right
              %a{:href => "/"} 
                %h3.white CoReading
            %li.text-center
              %a.white{:href => "/articles"} 文章
        %br
        %br
        %br
        .text-center
          = image_tag 'logo.png'
        .header-intro.show-for-large-only
          %span.spacer
          %h3.white 记录，分享
          %span.spacer
        %br
        %h2.white.text-center CoReading
        %p.white.text-center 协作阅读，分享经验
        %br
        .row
          .large-6.columns.large-centered.medium-10.medium-centered
            .row
              .large-6.medium-6.columns
                %a.button.full.black-bg.radius{:href => "/users/sign_up"} 注册
              .large-6.medium-6.columns
                %a.button.full.none-bg.radius{:href => "/users/sign_in"} 登录
  .page-2
    .row
      .large-12.columns.wrap.text-center
        %h3 CoReading 为阅读而作
        %br
        %br
        %p 这是一个开源的分享平台，你可以在这里阅读文章，包括阅读和批注文章，你只需要注册一个账号。
        %a.button.entry.radius{href: '/articles'} 
          %i.fa.fa-arrow-right
          &nbsp;
          进入
  .page-3
    .row
      .large-12.columns.wrap.text-center
        %h3.white 功能介绍
        %br
        %br
        %ul.large-block-grid-3.medium-block-grid-3.small-block-grid-1
          %li.box
            %h4.white 响应式设计
            %p.white 为您提高更好的用户体验。
            %br
            %br
            = image_tag 'features-search.png'
          %li.box
            %h4.white 协作阅读
            %p.white 您可以选择加入小组，与小组成员一起阅读。
            %br
            = image_tag 'features-reading.png'
          %li.box
            %h4.white 批注
            %p.white 
              你可以对正在阅读的文章进行批注，其他组员可以实时看到你的批注。
            %br
            = image_tag 'features-annotation.png'
  .page-4
    .row
      .large-12.columns.wrap.text-center
        %h3 开发人员
        %br
        %br
        .large-8.columns.large-centered.medium-12
          .large-5.small-3.columns.medium-6
            = image_tag 'me.png'
          .large-7.small-9.columns.medium-6
            %p.text-left Wendy,负责网站全栈开发。
  .page-5
    .row
      .large-12.columns.wrap.text-center
        %h3.white 加入我们
        %br
        .row
          .large-8.columns.large-centered.medium-10.medium-centered
            .row
              .large-6.medium-6.columns
                %a.button.git.full.black-bg.radius{href: 'https://github.com/wendycan/coreading', target: '_blank'} 
                  %i.fa.fa-github
                  GitHub
              .large-6.medium-6.columns
                %a.button.email.full.none-bg.radius{href: 'http://coreading.wendycan.org'} 
                  %i.fa.fa-book
                  CoReading
  .page-6.footer.hide-for-small-only
    .row.wrap
      .large-5.columns.large-centered.medium-5.medium-centered
        .row
          .large-6.columns.small-12.medium-6
            %h4.white 关于
            %p.text-left
              %a{:href => "/articles"} 博客
            %p.text-left
              %a{:href => "/articles"} 演示文稿
          .large-6.columns.small-12.medium-6
            %h4.white 友情链接
            %p.text-left
              %a{:href => "http://wendycan.org", target: '_blank'} wendy
            %p.text-left
              %a{:href => "http://daodao.wendycan.org", target: '_blank'} 刀刀故事
            %p.text-left
              %a{:href => "http://history.wendycan.org", target: '_blank'} wendy 故事

app/views/users/articles.html.haml
.row
  .large-12.columns
    #main-content.wrap
      %a.button.tiny{:href => "/articles/new"} 添加文章
      #u-articles
        .row.border-bottom
          .large-4.columns
            %h5 标题
          .large-2.columns
            %p 批注数
          .large-2.columns
            %p 来源
          .large-2.columns
            %p 权限
          .large-2.columns
            %p 创建时间
        - @articles.each do |article|
          .row.border-bottom
            .large-4.columns
              %h5= link_to article.title, article_path(article.id)
            .large-2.columns
              %p= article.annotations.length
            .large-2.columns
              - if article.path_type == 'pdf'
                %p 上传 pdf
              - else
                %p 在线
            .large-2.columns
              - if article.public == 0
                %span.label.radius 公开
              - if article.public == 1
                %p 
                  %span.label.radius 组 
                  %span= article.group.title
              - if article.public == 2
                %p 个人
            .large-2.columns
              %p= article.created_at.strftime("%m月%d号")
    = will_paginate @articles

= content_for :js_ext do
  :javascript
    $('.my-articles-btn').addClass('active');

app/views/users/group.html.haml
.wrap
  %h4 参与的组
  .user-groups
    %ul
      %li
        .row
          .large-5.columns
            %h5 组名
          .large-1.columns
            %span 成员数
          .large-1.columns
            %span 文章数
          .large-2.columns
            %span 管理员
          .large-2.columns
            %span 创建时间
          .large-1.columns
            %span= ''
      - @groups.each do |group|
        %li
          .row
            .large-5.columns
              %h5
                = link_to group.title, group_articles_path(group.id)
            .large-1.columns
              %span= group.users.length
            .large-1.columns
              %span= group.articles.length
            .large-2.columns
              %span= User.find(group.admin_id).email
            .large-2.columns
              %span= group.created_at.strftime("%m月%d号")
            .large-1.columns
              - if current_user.id == group.admin_id
                %span
                  = link_to edit_group_path(group) do
                    %i.fa.fa-pencil-square-o
              - else
                %span= ''
          .row
            .large-12.columns
              %p= group.desc
  %hr
  = link_to '创建组', new_group_path, :class => 'button tiny'

= content_for :js_ext do
  :javascript
    $('.my-groups-btn').addClass('active');